### ISSUE TITLE
How to import 32570_full.json to couchdb?

### ISSUE THREAD

**Issue by aisk** [ripple-unmaintained/ripplecharts#4]
I found that `node ledgerImporter.js all` will import ledger after `32570`, so how I import 32570_full.json into couchdb?

**Comment by deckar01** [comment]
`curl -X PUT localhost:5984/dbname/0000032570 -H 'Content-Type: application/json' -d @32570_full.json`

Replace "dbname" with the name you gave this db.
Note: The ID has to be the ledger index padded to 10 digits with 0s.

**Comment by aisk** [comment]
@deckar01 thx
