### ISSUE TITLE
Missing API routes

### ISSUE THREAD

**Issue by deckar01** [ripple-unmaintained/ripplecharts#5]
When setting up `ripplecharts-frontend` with `ripplecharts` I found that 2 of the routes that the frontend expects are not available in the `v2.0` branch:
- /api/totalnetworkvalue/ 404 (Not Found) 

```
Sorry, that API route doesn't seem to exist. Available paths are: /api/offersexercised/, /api/topmarkets/, /api/accountscreated/, /api/gatewaycapitalization/, /api/issuercapitalization/, /api/exchangerates/, /api/gettransaction/, /api/numtransactions/
```
- /api/totalvaluesent/ 404 (Not Found) 

```
Sorry, that API route doesn't seem to exist. Available paths are: /api/offersexercised/, /api/topmarkets/, /api/accountscreated/, /api/gatewaycapitalization/, /api/issuercapitalization/, /api/exchangerates/, /api/gettransaction/, /api/numtransactions/
```

Have those changes not been pushed yet, or do I need to look elsewhere?

**Comment by shekenahglory** [comment]
https://github.com/ripple/ripple-data-api

this is the code for the current backend

**Comment by deckar01** [comment]
Thanks!
